language: python
# Use new container-based Travis infrastructure.
sudo: false
# Cache pip packages.
cache: pip

# Try OS X.
os:
  - linux
  #- osx

#env:
#  - PYCRYPTO_VERSION=2.4.1
#  - PYCRYPTO_VERSION=2.6.1
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

matrix:
  allow_failures:
      # Just tests how PyInstaller performs with upcoming Python 3.6
      - python: "nightly"
      # Ignore failures from OS X.
      - os: osx


before_install:
  # TODO Review installing dependencies.
  # install extension using apt-get to save compiling
  # NB: Travis-CI uses Ubuntu 12.04 TLS, thus these are only available
  #     for Python 2.7.
  #- sudo apt-get update -qq
  #- sudo apt-get install -y python-gst0.10
  #- sudo apt-get install -y python-imaging
  #- sudo apt-get install -y python-matplotlib
  #- sudo apt-get install -y python-mysqldb
  #- sudo apt-get install -y python-numpy
  #- sudo apt-get install -y python-pyodbc
  #- sudo apt-get install -y python-qt4
  #- sudo apt-get install -y python-scipy
  #- sudo apt-get install -y python-wxgtk2.8
  ## fix a problem in travis, see
  ## https://github.com/travis-ci/travis-ci/issues/3106
  #- sudo rm -f /etc/apt/sources.list.d/travis_ci_zeromq3-source.list
  #- sudo apt-get install -y python-zmq
  #- sudo apt-get install -y libespeak1  # required by pyttsx

  # Compile bootloader
  - cd bootloader
  - python waf distclean all --no-lsb
  - cd ..

# Install dependencies.
install:
  # Install PyInstaller.
  - pip install -e .

  # Install dependencies for tests.
  # Download-progress bars break Travis's log view. Disable them by piping output
  # through another program (if output is not a tty, no progress bars)
  - pip install -r tests/requirements.txt | cat

script:
  # Run tests and speed them up by sending them to multiple CPUs.
  - py.test -n 5
  # TODO run tests with crypto
  #- ./runtests.py --all-with-crypto basic/*.py
