sudo: true

language: python

services:
- docker

# Cache pip packages. Explicitly name the pip-cache directory since we
# use a custom `install` step which annuls `cache: pip`.
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.pip-accel

os:
- linux

env:
  global:
  # shorten logging of pip-accel
  - PIP_ACCEL_LOG_FORMAT="%(name)-18s %(levelname)s %(message)s"
  matrix:
  - PY_VERSION=2.7
  - PY_VERSION=3.3
  - PY_VERSION=3.4
  - PY_VERSION=3.5
  - PY_VERSION=3.6

matrix:
  allow_failures:
  - env: PY_VERSION=3.6

script:
- ./travis-build.sh

notifications:
  irc:
    channels:
    - "irc.freenode.org#pyinstaller"
    use_notice: true
    # skip_join: true would require +n mode *not to be set on #pyinstaller
    skip_join: false
