# https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_allowed: false  # We have a blank template which assigns labels
contact_links:
  - name: Question about using PyInstaller
    url: "https://pyinstaller.org/ask-a-question/"
    about: Please see our guide on how to ask questions
  - name: My program won't compile properly!
    url: "https://pyinstaller.org/getting-help/"
    about: Please see our guide on getting help compiling your program
