name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events for develop and v4 branche.
on:
  push:
    branches:
      - 'develop'
      - 'v4'
      - 'debug-macos-py3101'
  pull_request:
    branches:
      - '**'
      - '!master'
      - '!pyup/**'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.10.0', '3.10.1', '3.10.2']
        os: ['macos-10.15', 'macos-11']
      fail-fast: false
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check for presence of Tcl/Tk 8.6 libraries
        run: |
          ls -l /usr/local/lib/libtcl* || echo "Tcl/Tk 8.6 not found!"

      - name: List contents of /usr/local/lib
        run: |
          ls -l /usr/local/lib

      - name: List contents of /usr/local/lib
        run: |
          ls -l /usr/local/Cellar/tcl-tk/*/*

      - name: Try importing tkinter
        run: python3 -c 'import tkinter'
