name: Lint

on:
  pull_request:  # Trigger on PRs to develop and v4
    branches:
      - develop
      - v4

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Get out of detached head state
      run: |
        git fetch origin ${{ github.base_ref }}
        git fetch origin ${{ github.ref }}
        git checkout FETCH_HEAD --
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install --upgrade bandit codespell flake8 wheel setuptools yapf==0.31.0 toml

    - name: Test that yapf has been applied
      # If this check fails for your PR, run `yapf -rip .`
      run: yapf --recursive --parallel --diff .

    - name: Run Lint
      run: |
        bandit --recursive  --skip B101,B102,B103,B105,B110,B112,B301,B302,B303,B306,B307,B318,B320,B403,B404,B405,B406,B408,B410,B504,B602,B603,B607,B608 .
        codespell --ignore-words-list=ba,bre,creat,datas,gir,glyh,seh,sur,te --skip="*.svg" || true
        flake8 .

    - name: Test Packaging
      run: |
        python setup.py sdist bdist_wheel
        pip install -v .
