name: Lint

on:
  pull_request:  # Trigger on PRs to develop and v4
    branches:
      - develop
      - v4

env:
  # Prevent setuptools from replacing distutils with its vendored version. There seem to be issues
  # between setuptools-provided distutils and pip 22.2 on python < 3.10, which results in failure
  # of the "Test Packaging" step.
  SETUPTOOLS_USE_DISTUTILS: not-today

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Get out of detached head state
      run: |
        git fetch origin ${{ github.base_ref }}
        git fetch origin ${{ github.ref }}
        git checkout FETCH_HEAD --
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -U flake8 wheel setuptools yapf==0.32.0 toml

    - name: Test that yapf has been applied
      # If this check fails for your PR, run `yapf -rip .`
      run: yapf --recursive --parallel --diff .

    - name: Run Lint
      run: flake8 .

    - name: Test Packaging
      run: |
        python setup.py sdist bdist_wheel
        pip install -v .
